baseURL = "https://docs.batterytracker.io/"
languageCode = "en-us"
title = "BatteryTracker Documentation"
theme = "docs-theme"
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
    version = "v0.1.0"
    siteUrl = "http://localhost:1313"
    docsUrl = "http://localhost:1313"

[menu]
    [[menu.main]]
        identifier = "guides"
        title = "Guides"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1